## Makefile for running examples
## Author: steven martell <martell.steve@gmail.com>
## targets:

## Macros
subdirs = AREA27 AREA2W CC PRD QCI SOG WCVI
makeopt = default

.PHONY: default $(subdirs)

## Targets
default: $(subdirs)
$(subdirs):
	@echo $@
	cd $@ && $(MAKE) all




