echo off
del variance /Q /F
del eigv.rpt /Q /F
del iscam.cpp /Q /F
del *.bar /Q /F
del *.cov /Q /F
del *.cor /Q /F
del *.dep /Q /F
del *.hes /Q /F
del *.log /Q /F
del *.aux /Q /F
del *.out /Q /F
del *.pdf /Q /F
del *.txt /Q /F
del *.eva /Q /F
del *.exe /Q /F
del *.htp /Q /F
del *.obj /Q /F
del *.par /Q /F
del *.rep /Q /F
del *.std /Q /F
del *.p0* /Q /F
del *.p1* /Q /F
del *.r0* /Q /F
del *.r1* /Q /F
del *.b0* /Q /F
del *.b1* /Q /F
del *.res /Q /F
del *.d   /Q /F
del *.eql /Q /F
